/* Copyright 2016 Sebastian Meyer (seibushin.de)
 *
 * NO LICENSE
 * YOU MAY NOT REPRODUCE, DISTRIBUTE, OR CREATE DERIVATIVE WORKS FROM MY WORK
 *
 */

package de.seibushin.bodyArchitect.model.nutrition;

import javax.persistence.*;
import java.text.MessageFormat;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "FOODS")
public class Food {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "FOOD_ID")
    private int id;

    private String name;
    private double kcal;
    private double protein;
    private double carbs;
    private double sugar;
    private double fat;
    private double weight;
    private double portion;

    @OneToMany(mappedBy = "food")
    private Set<MealFood> mealFoods = new HashSet<MealFood>();

    /**
     * no argument constructor required for hibernate
     */
    public Food() {

    }

    /**
     * constructor without id, id is generated by the database
     *
     * @param name - name
     * @param kcal - kcal
     * @param protein - proteins
     * @param carbs - carbs
     * @param sugar - sugar
     * @param fat - fat
     * @param weight - weight
     * @param portion - portion
     */
    public Food(String name, double kcal, double protein, double carbs, double sugar, double fat, double weight, double portion) {
        this.name = name;
        this.kcal = kcal;
        this.protein = protein;
        this.carbs = carbs;
        this.sugar = sugar;
        this.fat = fat;
        this.weight = weight;
        this.portion = portion;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getKcal() {
        return kcal;
    }

    public void setKcal(int kcal) {
        this.kcal = kcal;
    }

    public double getProtein() {
        return protein;
    }

    public void setProtein(int protein) {
        this.protein = protein;
    }

    public double getCarbs() {
        return carbs;
    }

    public void setCarbs(int carbs) {
        this.carbs = carbs;
    }

    public double getSugar() {
        return sugar;
    }

    public void setSugar(int sugar) {
        this.sugar = sugar;
    }

    public double getFat() {
        return fat;
    }

    public void setFat(int fat) {
        this.fat = fat;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }

    public double getPortion() {
        return portion;
    }

    public void setPortion(int portion) {
        this.portion = portion;
    }

    public Set<MealFood> getMealFoods() {
        return mealFoods;
    }

    public void setMealFoods(Set<MealFood> mealFoods) {
        this.mealFoods = mealFoods;
    }

    @Override
    public String toString() {
        return MessageFormat.format("{8} {0}: {1}kcal - {2}g (C {3}({4}), P {5}, F {6}) -> {7}g", this.name, this.kcal, this.weight, this.carbs, this.sugar, this.protein, this.fat, this.portion, this.id);
    }
}
